const resetContext = async (ControlloMyContext: any) => {
  ControlloMyContext.setA2_TabRig_informazioni_generali_D_01_data("");
  ControlloMyContext.setA2_TabRig_informazioni_generali_D_02_ora_inizio("");
  ControlloMyContext.setA2_TabRig_informazioni_generali_D_03_ora_fine("");
  ControlloMyContext.setA2_TabRig_informazioni_generali_D_04_numero_giorno_settimana(
    undefined
  );
  ControlloMyContext.setA2_TabRig_informazioni_generali_D_05_latitudine(
    undefined
  );
  ControlloMyContext.setA2_TabRig_informazioni_generali_D_06_longitudine(
    undefined
  );
  ControlloMyContext.setA2_TabRig_informazioni_generali_D_07_provincia("");
  ControlloMyContext.setA2_TabRig_informazioni_generali_D_08_comune("");
  ControlloMyContext.setA2_TabRig_informazioni_generali_D_09_codice_avviamento_postale(
    undefined
  );
  ControlloMyContext.setA2_TabRig_informazioni_generali_D_10_regione("");
  ControlloMyContext.setA2_TabRig_informazioni_generali_D_11_indirizzo("");
  ControlloMyContext.setA2_TabRig_informazioni_generali_D_12_nome_operatore("");
  ControlloMyContext.setA2_TabRig_informazioni_generali_D_13_cognome_operatore(
    ""
  );
  ControlloMyContext.setA2_TabRig_informazioni_generali_id_record(undefined);
  ControlloMyContext.setA2_TabRig_informazioni_generali_D_14_stato("");
  ControlloMyContext.setA2_TabRig_informazioni_generali_D_15_targa("");
  ControlloMyContext.setA2_TabRig_informazioni_generali_D_16_nome_conducente(
    ""
  );
  ControlloMyContext.setA2_TabRig_informazioni_generali_D_17_cognome_conducente(
    ""
  );
  ControlloMyContext.setA2_TabRig_informazioni_generali_D_18_nome_proprietario(
    ""
  );
  ControlloMyContext.setA2_TabRig_informazioni_generali_D_19_cognome_proprietario(
    ""
  );
  ControlloMyContext.setA2_TabRig_informazioni_generali_D_20_numero_patente("");
  ControlloMyContext.setA2_TabRig_informazioni_generali_D_21_numero_carta_id(
    ""
  );
  ControlloMyContext.setA2_TabRig_informazioni_generali_D_22_numero_passaporto(
    ""
  );
  ControlloMyContext.setA2_TabRig_informazioni_generali_D_23_marca_modello_veicolo(
    ""
  );
  ControlloMyContext.setA2_TabRig_informazioni_generali_D_24_cognome_nome_operatore(
    ""
  );
  ControlloMyContext.setA2_TabRig_informazioni_generali_D_24_cognome_nome_operatore_2(
    ""
  );
  ControlloMyContext.setA2_TabRig_informazioni_generali_D_25_norme_violate([]);
  ControlloMyContext.setA2_TabRig_informazioni_generali_D_27_controlli_eseguiti(
    []
  );
  ControlloMyContext.setA2_TabRig_informazioni_generali_D_29_tipo_mezzo("");
  ControlloMyContext.setA2_TabRig_informazioni_generali_D_30_note("");
  ControlloMyContext.setA2_TabRig_informazioni_generali_D_31_carta_circolazione_ritirata(
    undefined
  );
  ControlloMyContext.setA2_TabRig_informazioni_generali_D_32_certificato_assicurazione_ritirato(
    undefined
  );
  ControlloMyContext.setA2_TabRig_informazioni_generali_D_33_verifica_revisione(
    undefined
  );
  ControlloMyContext.setA2_TabRig_informazioni_generali_D_34_verifica_assicurazione(
    undefined
  );
  ControlloMyContext.setA2_TabRig_informazioni_generali_D_35_verifica_scarico(
    undefined
  );
  ControlloMyContext.setA2_TabRig_informazioni_generali_D_36_verifica_cinture_sicurezza(
    undefined
  );
  ControlloMyContext.setA2_TabRig_informazioni_generali_D_37_verifica_pneumatici(
    undefined
  );
  ControlloMyContext.setA2_TabRig_informazioni_generali_D_38_verifica_luci(
    undefined
  );
  ControlloMyContext.setA2_TabRig_informazioni_generali_D_39_targa_rimorchio(
    ""
  );

  //A3_02_TabRig_PatenteGuida---------------------------------------------------------------------

  ControlloMyContext.setA3_02_TabRig_PatenteGuida_id_record(undefined);
  ControlloMyContext.setA3_02_TabRig_PatenteGuida_N_02_cognome_conducente("");
  ControlloMyContext.setA3_02_TabRig_PatenteGuida_N_03_nome_conducente("");
  ControlloMyContext.setA3_02_TabRig_PatenteGuida_N_04_data_nascita_conducente(
    ""
  );
  ControlloMyContext.setA3_02_TabRig_PatenteGuida_N_05_luogo_nascita_conducente(
    ""
  );
  ControlloMyContext.setA3_02_TabRig_PatenteGuida_N_06_data_emissione_documento_conducente(
    ""
  );
  ControlloMyContext.setA3_02_TabRig_PatenteGuida_N_07_data_scadenza_documento_conducente(
    ""
  );
  ControlloMyContext.setA3_02_TabRig_PatenteGuida_N_08_rilasciata_da_conducente(
    ""
  );
  ControlloMyContext.setA3_02_TabRig_PatenteGuida_N_09_numero_documento_conducente(
    ""
  );
  ControlloMyContext.setA3_02_TabRig_PatenteGuida_N_10_categoria_patente_conducente(
    []
  );
  ControlloMyContext.setA3_02_TabRig_PatenteGuida_N_11_annotazioni_restrizioni_conducente(
    ""
  );
  ControlloMyContext.setA3_02_TabRig_PatenteGuida_N_02_cognome_passeggero_1("");
  ControlloMyContext.setA3_02_TabRig_PatenteGuida_N_03_nome_passeggero_1("");
  ControlloMyContext.setA3_02_TabRig_PatenteGuida_N_04_data_nascita_passeggero_1(
    ""
  );
  ControlloMyContext.setA3_02_TabRig_PatenteGuida_N_05_luogo_nascita_passeggero_1(
    ""
  );
  ControlloMyContext.setA3_02_TabRig_PatenteGuida_N_06_data_emissione_documento_passeggero_1(
    ""
  );
  ControlloMyContext.setA3_02_TabRig_PatenteGuida_N_07_data_scadenza_documento_passeggero_1(
    ""
  );
  ControlloMyContext.setA3_02_TabRig_PatenteGuida_N_08_rilasciata_da_passeggero_1(
    ""
  );
  ControlloMyContext.setA3_02_TabRig_PatenteGuida_N_09_numero_documento_passeggero_1(
    ""
  );
  ControlloMyContext.setA3_02_TabRig_PatenteGuida_N_10_categoria_patente_passeggero_1(
    ""
  );
  ControlloMyContext.setA3_02_TabRig_PatenteGuida_N_11_annotazioni_restrizioni_passeggero_1(
    ""
  );
  ControlloMyContext.setA3_02_TabRig_PatenteGuida_N_02_cognome_passeggero_2("");
  ControlloMyContext.setA3_02_TabRig_PatenteGuida_N_03_nome_passeggero_2("");
  ControlloMyContext.setA3_02_TabRig_PatenteGuida_N_03_nome_passeggero_2("");
  ControlloMyContext.setA3_02_TabRig_PatenteGuida_N_04_data_nascita_passeggero_2(
    ""
  );
  ControlloMyContext.setA3_02_TabRig_PatenteGuida_N_05_luogo_nascita_passeggero_2(
    ""
  );
  ControlloMyContext.setA3_02_TabRig_PatenteGuida_N_06_data_emissione_documento_passeggero_2(
    ""
  );

  ControlloMyContext.setA3_02_TabRig_PatenteGuida_N_07_data_scadenza_documento_passeggero_2(
    ""
  );

  ControlloMyContext.setA3_02_TabRig_PatenteGuida_N_08_rilasciata_da_passeggero_2(
    ""
  );
  ControlloMyContext.setA3_02_TabRig_PatenteGuida_N_09_numero_documento_passeggero_2(
    ""
  );
  ControlloMyContext.setA3_02_TabRig_PatenteGuida_N_10_categoria_patente_passeggero_2(
    ""
  );
  ControlloMyContext.setA3_02_TabRig_PatenteGuida_N_11_annotazioni_restrizioni_passeggero_2(
    ""
  );

  ControlloMyContext.setA3_02_TabRig_PatenteGuida_N_02_cognome_passeggero_3("");
  ControlloMyContext.setA3_02_TabRig_PatenteGuida_N_03_nome_passeggero_3("");
  ControlloMyContext.setA3_02_TabRig_PatenteGuida_N_04_data_nascita_passeggero_3(
    ""
  );
  ControlloMyContext.setA3_02_TabRig_PatenteGuida_N_05_luogo_nascita_passeggero_3(
    ""
  );
  ControlloMyContext.setA3_02_TabRig_PatenteGuida_N_06_data_emissione_documento_passeggero_3(
    ""
  );

  ControlloMyContext.setA3_02_TabRig_PatenteGuida_N_07_data_scadenza_documento_passeggero_3(
    ""
  );

  ControlloMyContext.setA3_02_TabRig_PatenteGuida_N_08_rilasciata_da_passeggero_3(
    ""
  );
  ControlloMyContext.setA3_02_TabRig_PatenteGuida_N_09_numero_documento_passeggero_3(
    ""
  );
  ControlloMyContext.setA3_02_TabRig_PatenteGuida_N_10_categoria_patente_passeggero_3(
    ""
  );
  ControlloMyContext.setA3_02_TabRig_PatenteGuida_N_11_annotazioni_restrizioni_passeggero_3(
    ""
  );

  ControlloMyContext.setA3_02_TabRig_PatenteGuida_N_02_cognome_passeggero_4("");
  ControlloMyContext.setA3_02_TabRig_PatenteGuida_N_03_nome_passeggero_4("");
  ControlloMyContext.setA3_02_TabRig_PatenteGuida_N_04_data_nascita_passeggero_4(
    ""
  );
  ControlloMyContext.setA3_02_TabRig_PatenteGuida_N_05_luogo_nascita_passeggero_4(
    ""
  );
  ControlloMyContext.setA3_02_TabRig_PatenteGuida_N_06_data_emissione_documento_passeggero_4(
    ""
  );

  ControlloMyContext.setA3_02_TabRig_PatenteGuida_N_07_data_scadenza_documento_passeggero_4(
    ""
  );

  ControlloMyContext.setA3_02_TabRig_PatenteGuida_N_08_rilasciata_da_passeggero_4(
    ""
  );
  ControlloMyContext.setA3_02_TabRig_PatenteGuida_N_09_numero_documento_passeggero_4(
    ""
  );
  ControlloMyContext.setA3_02_TabRig_PatenteGuida_N_10_categoria_patente_passeggero_4(
    ""
  );
  ControlloMyContext.setA3_02_TabRig_PatenteGuida_N_11_annotazioni_restrizioni_passeggero_4(
    ""
  );

  ControlloMyContext.setA3_02_TabRig_PatenteGuida_N_02_cognome_passeggero_5("");
  ControlloMyContext.setA3_02_TabRig_PatenteGuida_N_03_nome_passeggero_5("");
  ControlloMyContext.setA3_02_TabRig_PatenteGuida_N_04_data_nascita_passeggero_5(
    ""
  );
  ControlloMyContext.setA3_02_TabRig_PatenteGuida_N_05_luogo_nascita_passeggero_5(
    ""
  );
  ControlloMyContext.setA3_02_TabRig_PatenteGuida_N_06_data_emissione_documento_passeggero_5(
    ""
  );

  ControlloMyContext.setA3_02_TabRig_PatenteGuida_N_07_data_scadenza_documento_passeggero_5(
    ""
  );

  ControlloMyContext.setA3_02_TabRig_PatenteGuida_N_08_rilasciata_da_passeggero_5(
    ""
  );
  ControlloMyContext.setA3_02_TabRig_PatenteGuida_N_09_numero_documento_passeggero_5(
    ""
  );
  ControlloMyContext.setA3_02_TabRig_PatenteGuida_N_10_categoria_patente_passeggero_5(
    ""
  );
  ControlloMyContext.setA3_02_TabRig_PatenteGuida_N_11_annotazioni_restrizioni_passeggero_5(
    ""
  );

  //A3_03_TabRig_CartaIdentita---------------------------------------------------------------

  ControlloMyContext.ControlloMyContext.setA3_03_TabRig_CartaIdentita_id_record(
    undefined
  );
  ControlloMyContext.ControlloMyContext.setA3_03_TabRig_CartaIdentita_N_02_comune_ufficio_emettitore_conducente(
    ""
  );
  ControlloMyContext.ControlloMyContext.setA3_03_TabRig_CartaIdentita_N_03_cognome_conducente(
    ""
  );
  ControlloMyContext.ControlloMyContext.setA3_03_TabRig_CartaIdentita_N_04_nome_conducente(
    ""
  );
  ControlloMyContext.ControlloMyContext.setA3_03_TabRig_CartaIdentita_N_05_data_nascita_conducente(
    ""
  );
  ControlloMyContext.ControlloMyContext.setA3_03_TabRig_CartaIdentita_N_06_luogo_nascita_conducente(
    ""
  );
  ControlloMyContext.ControlloMyContext.setA3_03_TabRig_CartaIdentita_N_08_sesso_conducente(
    ""
  );
  ControlloMyContext.ControlloMyContext.setA3_03_TabRig_CartaIdentita_N_09_statura_conducente(
    ""
  );
  ControlloMyContext.ControlloMyContext.setA3_03_TabRig_CartaIdentita_N_10_occhi_conducente(
    ""
  );
  ControlloMyContext.ControlloMyContext.setA3_03_TabRig_CartaIdentita_N_11_cittadinanza_conducente(
    ""
  );
  ControlloMyContext.ControlloMyContext.setA3_03_TabRig_CartaIdentita_N_12_codice_fiscale_conducente(
    ""
  );
  ControlloMyContext.ControlloMyContext.setA3_03_TabRig_CartaIdentita_N_13_residenza_conducente(
    ""
  );
  ControlloMyContext.ControlloMyContext.setA3_03_TabRig_CartaIdentita_N_14_professione_conducente(
    ""
  );
  ControlloMyContext.ControlloMyContext.setA3_03_TabRig_CartaIdentita_N_15_stato_civile_conducente(
    ""
  );
  ControlloMyContext.ControlloMyContext.setA3_03_TabRig_CartaIdentita_N_16_eventuale_non_validita_per_espatrio_conducente(
    ""
  );
  ControlloMyContext.ControlloMyContext.setA3_03_TabRig_CartaIdentita_N_17_nome_cognome_padre_nel_caso_minore_conducente(
    ""
  );
  ControlloMyContext.ControlloMyContext.setA3_03_TabRig_CartaIdentita_N_23_nome_cognome_madre_nel_caso_minore_conducente(
    ""
  );
  ControlloMyContext.ControlloMyContext.setA3_03_TabRig_CartaIdentita_N_18_estremi_atto_nascita_conducente(
    ""
  );
  ControlloMyContext.ControlloMyContext.setA3_03_TabRig_CartaIdentita_N_19_comune_di_iscrizione_AIRE_conducente(
    ""
  );
  ControlloMyContext.ControlloMyContext.setA3_03_TabRig_CartaIdentita_N_20_numero_documento_conducente(
    ""
  );
  ControlloMyContext.ControlloMyContext.setA3_03_TabRig_CartaIdentita_N_21_data_emissione_documento_conducente(
    ""
  );
  ControlloMyContext.ControlloMyContext.setA3_03_TabRig_CartaIdentita_N_22_data_scadenza_documento_conducente(
    ""
  );
  ControlloMyContext.ControlloMyContext.setA3_03_TabRig_CartaIdentita_N_23_nome_cognome_madre_nel_caso_minore_conducente(
    ""
  );

  ControlloMyContext.setA3_03_TabRig_CartaIdentita_N_02_comune_ufficio_emettitore_passeggero_1(
    ""
  );
  ControlloMyContext.setA3_03_TabRig_CartaIdentita_N_03_cognome_passeggero_1(
    ""
  );
  ControlloMyContext.setA3_03_TabRig_CartaIdentita_N_04_nome_passeggero_1("");
  ControlloMyContext.setA3_03_TabRig_CartaIdentita_N_05_data_nascita_passeggero_1(
    ""
  );
  ControlloMyContext.setA3_03_TabRig_CartaIdentita_N_06_luogo_nascita_passeggero_1(
    ""
  );
  ControlloMyContext.setA3_03_TabRig_CartaIdentita_N_08_sesso_passeggero_1("");
  ControlloMyContext.setA3_03_TabRig_CartaIdentita_N_09_statura_passeggero_1(
    ""
  );
  ControlloMyContext.setA3_03_TabRig_CartaIdentita_N_10_occhi_passeggero_1("");
  ControlloMyContext.setA3_03_TabRig_CartaIdentita_N_11_cittadinanza_passeggero_1(
    ""
  );
  ControlloMyContext.setA3_03_TabRig_CartaIdentita_N_12_codice_fiscale_passeggero_1(
    ""
  );
  ControlloMyContext.setA3_03_TabRig_CartaIdentita_N_13_residenza_passeggero_1(
    ""
  );
  ControlloMyContext.setA3_03_TabRig_CartaIdentita_N_14_professione_passeggero_1(
    ""
  );
  ControlloMyContext.setA3_03_TabRig_CartaIdentita_N_15_stato_civile_passeggero_1(
    ""
  );
  ControlloMyContext.setA3_03_TabRig_CartaIdentita_N_16_eventuale_non_validita_per_espatrio_passeggero_1(
    ""
  );
  ControlloMyContext.setA3_03_TabRig_CartaIdentita_N_17_nome_cognome_padre_nel_caso_minore_passeggero_1(
    ""
  );
  ControlloMyContext.setA3_03_TabRig_CartaIdentita_N_23_nome_cognome_madre_nel_caso_minore_passeggero_1(
    ""
  );
  ControlloMyContext.setA3_03_TabRig_CartaIdentita_N_18_estremi_atto_nascita_passeggero_1(
    ""
  );
  ControlloMyContext.setA3_03_TabRig_CartaIdentita_N_19_comune_di_iscrizione_AIRE_passeggero_1(
    ""
  );
  ControlloMyContext.setA3_03_TabRig_CartaIdentita_N_20_numero_documento_passeggero_1(
    ""
  );
  ControlloMyContext.setA3_03_TabRig_CartaIdentita_N_21_data_emissione_documento_passeggero_1(
    ""
  );
  ControlloMyContext.setA3_03_TabRig_CartaIdentita_N_22_data_scadenza_documento_passeggero_1(
    ""
  );
  ControlloMyContext.setA3_03_TabRig_CartaIdentita_N_02_comune_ufficio_emettitore_passeggero_2(
    ""
  );
  ControlloMyContext.setA3_03_TabRig_CartaIdentita_N_03_cognome_passeggero_2(
    ""
  );
  ControlloMyContext.setA3_03_TabRig_CartaIdentita_N_04_nome_passeggero_2("");
  ControlloMyContext.setA3_03_TabRig_CartaIdentita_N_05_data_nascita_passeggero_2(
    ""
  );
  ControlloMyContext.setA3_03_TabRig_CartaIdentita_N_06_luogo_nascita_passeggero_2(
    ""
  );
  ControlloMyContext.setA3_03_TabRig_CartaIdentita_N_08_sesso_passeggero_2("");
  ControlloMyContext.setA3_03_TabRig_CartaIdentita_N_09_statura_passeggero_2(
    ""
  );
  ControlloMyContext.setA3_03_TabRig_CartaIdentita_N_10_occhi_passeggero_2("");
  ControlloMyContext.setA3_03_TabRig_CartaIdentita_N_11_cittadinanza_passeggero_2(
    ""
  );
  ControlloMyContext.setA3_03_TabRig_CartaIdentita_N_12_codice_fiscale_passeggero_2(
    ""
  );
  ControlloMyContext.setA3_03_TabRig_CartaIdentita_N_13_residenza_passeggero_2(
    ""
  );
  ControlloMyContext.setA3_03_TabRig_CartaIdentita_N_14_professione_passeggero_2(
    ""
  );
  ControlloMyContext.setA3_03_TabRig_CartaIdentita_N_15_stato_civile_passeggero_2(
    ""
  );
  ControlloMyContext.setA3_03_TabRig_CartaIdentita_N_16_eventuale_non_validita_per_espatrio_passeggero_2(
    ""
  );
  ControlloMyContext.setA3_03_TabRig_CartaIdentita_N_17_nome_cognome_padre_nel_caso_minore_passeggero_2(
    ""
  );

  ControlloMyContext.setA3_03_TabRig_CartaIdentita_N_23_nome_cognome_madre_nel_caso_minore_passeggero_2(
    ""
  );
  ControlloMyContext.setA3_03_TabRig_CartaIdentita_N_18_estremi_atto_nascita_passeggero_2(
    ""
  );
  ControlloMyContext.setA3_03_TabRig_CartaIdentita_N_19_comune_di_iscrizione_AIRE_passeggero_2(
    ""
  );
  ControlloMyContext.setA3_03_TabRig_CartaIdentita_N_20_numero_documento_passeggero_2(
    ""
  );
  ControlloMyContext.setA3_03_TabRig_CartaIdentita_N_21_data_emissione_documento_passeggero_2(
    ""
  );
  ControlloMyContext.setA3_03_TabRig_CartaIdentita_N_22_data_scadenza_documento_passeggero_2(
    ""
  );
  ControlloMyContext.setA3_03_TabRig_CartaIdentita_N_02_comune_ufficio_emettitore_passeggero_3(
    ""
  );
  ControlloMyContext.setA3_03_TabRig_CartaIdentita_N_03_cognome_passeggero_3(
    ""
  );
  ControlloMyContext.setA3_03_TabRig_CartaIdentita_N_04_nome_passeggero_3("");
  ControlloMyContext.setA3_03_TabRig_CartaIdentita_N_05_data_nascita_passeggero_3(
    ""
  );
  ControlloMyContext.setA3_03_TabRig_CartaIdentita_N_06_luogo_nascita_passeggero_3(
    ""
  );
  ControlloMyContext.setA3_03_TabRig_CartaIdentita_N_08_sesso_passeggero_3("");
  ControlloMyContext.setA3_03_TabRig_CartaIdentita_N_09_statura_passeggero_3(
    ""
  );
  ControlloMyContext.setA3_03_TabRig_CartaIdentita_N_10_occhi_passeggero_3("");
  ControlloMyContext.setA3_03_TabRig_CartaIdentita_N_11_cittadinanza_passeggero_3(
    ""
  );
  ControlloMyContext.setA3_03_TabRig_CartaIdentita_N_12_codice_fiscale_passeggero_3(
    ""
  );
  ControlloMyContext.setA3_03_TabRig_CartaIdentita_N_13_residenza_passeggero_3(
    ""
  );
  ControlloMyContext.setA3_03_TabRig_CartaIdentita_N_14_professione_passeggero_3(
    ""
  );
  ControlloMyContext.setA3_03_TabRig_CartaIdentita_N_15_stato_civile_passeggero_3(
    ""
  );

  ControlloMyContext.setA3_03_TabRig_CartaIdentita_N_16_eventuale_non_validita_per_espatrio_passeggero_3(
    ""
  );

  ControlloMyContext.setA3_03_TabRig_CartaIdentita_N_17_nome_cognome_padre_nel_caso_minore_passeggero_3(
    ""
  );

  ControlloMyContext.setA3_03_TabRig_CartaIdentita_N_23_nome_cognome_madre_nel_caso_minore_passeggero_3(
    ""
  );
  ControlloMyContext.setA3_03_TabRig_CartaIdentita_N_18_estremi_atto_nascita_passeggero_3(
    ""
  );
  ControlloMyContext.setA3_03_TabRig_CartaIdentita_N_19_comune_di_iscrizione_AIRE_passeggero_3(
    ""
  );
  ControlloMyContext.setA3_03_TabRig_CartaIdentita_N_20_numero_documento_passeggero_3(
    ""
  );
  ControlloMyContext.setA3_03_TabRig_CartaIdentita_N_21_data_emissione_documento_passeggero_3(
    ""
  );
  ControlloMyContext.setA3_03_TabRig_CartaIdentita_N_22_data_scadenza_documento_passeggero_3(
    ""
  );

  ControlloMyContext.setA3_03_TabRig_CartaIdentita_N_02_comune_ufficio_emettitore_passeggero_4(
    ""
  );
  ControlloMyContext.setA3_03_TabRig_CartaIdentita_N_03_cognome_passeggero_4(
    ""
  );
  ControlloMyContext.setA3_03_TabRig_CartaIdentita_N_04_nome_passeggero_4("");
  ControlloMyContext.setA3_03_TabRig_CartaIdentita_N_05_data_nascita_passeggero_4(
    ""
  );
  ControlloMyContext.setA3_03_TabRig_CartaIdentita_N_06_luogo_nascita_passeggero_4(
    ""
  );
  ControlloMyContext.setA3_03_TabRig_CartaIdentita_N_08_sesso_passeggero_4("");
  ControlloMyContext.setA3_03_TabRig_CartaIdentita_N_09_statura_passeggero_4(
    ""
  );
  ControlloMyContext.setA3_03_TabRig_CartaIdentita_N_10_occhi_passeggero_4("");
  ControlloMyContext.setA3_03_TabRig_CartaIdentita_N_11_cittadinanza_passeggero_4(
    ""
  );
  ControlloMyContext.setA3_03_TabRig_CartaIdentita_N_12_codice_fiscale_passeggero_4(
    ""
  );
  ControlloMyContext.setA3_03_TabRig_CartaIdentita_N_13_residenza_passeggero_4(
    ""
  );
  ControlloMyContext.setA3_03_TabRig_CartaIdentita_N_14_professione_passeggero_4(
    ""
  );
  ControlloMyContext.setA3_03_TabRig_CartaIdentita_N_15_stato_civile_passeggero_4(
    ""
  );

  ControlloMyContext.setA3_03_TabRig_CartaIdentita_N_16_eventuale_non_validita_per_espatrio_passeggero_4(
    ""
  );

  ControlloMyContext.setA3_03_TabRig_CartaIdentita_N_17_nome_cognome_padre_nel_caso_minore_passeggero_4(
    ""
  );

  ControlloMyContext.setA3_03_TabRig_CartaIdentita_N_23_nome_cognome_madre_nel_caso_minore_passeggero_4(
    ""
  );
  ControlloMyContext.setA3_03_TabRig_CartaIdentita_N_18_estremi_atto_nascita_passeggero_4(
    ""
  );
  ControlloMyContext.setA3_03_TabRig_CartaIdentita_N_19_comune_di_iscrizione_AIRE_passeggero_4(
    ""
  );
  ControlloMyContext.setA3_03_TabRig_CartaIdentita_N_20_numero_documento_passeggero_4(
    ""
  );
  ControlloMyContext.setA3_03_TabRig_CartaIdentita_N_21_data_emissione_documento_passeggero_4(
    ""
  );
  ControlloMyContext.setA3_03_TabRig_CartaIdentita_N_22_data_scadenza_documento_passeggero_4(
    ""
  );
  ControlloMyContext.setA3_03_TabRig_CartaIdentita_N_02_comune_ufficio_emettitore_passeggero_5(
    ""
  );
  ControlloMyContext.setA3_03_TabRig_CartaIdentita_N_03_cognome_passeggero_5(
    ""
  );
  ControlloMyContext.setA3_03_TabRig_CartaIdentita_N_04_nome_passeggero_5("");
  ControlloMyContext.setA3_03_TabRig_CartaIdentita_N_05_data_nascita_passeggero_5(
    ""
  );
  ControlloMyContext.setA3_03_TabRig_CartaIdentita_N_06_luogo_nascita_passeggero_5(
    ""
  );
  ControlloMyContext.setA3_03_TabRig_CartaIdentita_N_08_sesso_passeggero_5("");
  ControlloMyContext.setA3_03_TabRig_CartaIdentita_N_09_statura_passeggero_5(
    ""
  );
  ControlloMyContext.setA3_03_TabRig_CartaIdentita_N_10_occhi_passeggero_5("");
  ControlloMyContext.setA3_03_TabRig_CartaIdentita_N_11_cittadinanza_passeggero_5(
    ""
  );
  ControlloMyContext.setA3_03_TabRig_CartaIdentita_N_12_codice_fiscale_passeggero_5(
    ""
  );
  ControlloMyContext.setA3_03_TabRig_CartaIdentita_N_13_residenza_passeggero_5(
    ""
  );
  ControlloMyContext.setA3_03_TabRig_CartaIdentita_N_14_professione_passeggero_5(
    ""
  );
  ControlloMyContext.setA3_03_TabRig_CartaIdentita_N_15_stato_civile_passeggero_5(
    ""
  );

  ControlloMyContext.setA3_03_TabRig_CartaIdentita_N_16_eventuale_non_validita_per_espatrio_passeggero_5(
    ""
  );

  ControlloMyContext.setA3_03_TabRig_CartaIdentita_N_17_nome_cognome_padre_nel_caso_minore_passeggero_5(
    ""
  );

  ControlloMyContext.setA3_03_TabRig_CartaIdentita_N_23_nome_cognome_madre_nel_caso_minore_passeggero_5(
    ""
  );
  ControlloMyContext.setA3_03_TabRig_CartaIdentita_N_18_estremi_atto_nascita_passeggero_5(
    ""
  );
  ControlloMyContext.setA3_03_TabRig_CartaIdentita_N_19_comune_di_iscrizione_AIRE_passeggero_5(
    ""
  );
  ControlloMyContext.setA3_03_TabRig_CartaIdentita_N_20_numero_documento_passeggero_5(
    ""
  );
  ControlloMyContext.setA3_03_TabRig_CartaIdentita_N_21_data_emissione_documento_passeggero_5(
    ""
  );
  ControlloMyContext.setA3_03_TabRig_CartaIdentita_N_22_data_scadenza_documento_passeggero_5(
    ""
  );

  //A3_04_TabRig_Passaporto---------------------------------------------------------------

  ControlloMyContext.ControlloMyContext.setA3_04_TabRig_Passaporto_id_record(
    undefined
  );
  ControlloMyContext.ControlloMyContext.setA3_04_TabRig_Passaporto_N_02_tipo_conducente(
    ""
  );
  ControlloMyContext.ControlloMyContext.setA3_04_TabRig_Passaporto_N_03_codice_paese_conducente(
    ""
  );
  ControlloMyContext.ControlloMyContext.setA3_04_TabRig_Passaporto_N_04_numero_passaporto_conducente(
    ""
  );
  ControlloMyContext.ControlloMyContext.setA3_04_TabRig_Passaporto_N_05_cognome_conducente(
    ""
  );
  ControlloMyContext.ControlloMyContext.setA3_04_TabRig_Passaporto_N_06_nome_conducente(
    ""
  );
  ControlloMyContext.ControlloMyContext.setA3_04_TabRig_Passaporto_N_07_cittadinanza_conducente(
    ""
  );
  ControlloMyContext.ControlloMyContext.setA3_04_TabRig_Passaporto_N_08_data_nascita_conducente(
    ""
  );
  ControlloMyContext.ControlloMyContext.setA3_04_TabRig_Passaporto_N_09_luogo_nascita_conducente(
    ""
  );
  ControlloMyContext.ControlloMyContext.setA3_04_TabRig_Passaporto_N_10_sesso_conducente(
    ""
  );
  ControlloMyContext.ControlloMyContext.setA3_04_TabRig_Passaporto_N_11_data_emissione_documento_conducente(
    ""
  );
  ControlloMyContext.ControlloMyContext.setA3_04_TabRig_Passaporto_N_12_data_scadenza_documento_conducente(
    ""
  );
  ControlloMyContext.ControlloMyContext.setA3_04_TabRig_Passaporto_N_13_autorita_emittente_conducente(
    ""
  );
  ControlloMyContext.setA3_04_TabRig_Passaporto_N_02_tipo_passeggero_1("");
  ControlloMyContext.setA3_04_TabRig_Passaporto_N_03_codice_paese_passeggero_1(
    ""
  );
  ControlloMyContext.setA3_04_TabRig_Passaporto_N_04_numero_passaporto_passeggero_1(
    ""
  );
  ControlloMyContext.setA3_04_TabRig_Passaporto_N_05_cognome_passeggero_1("");
  ControlloMyContext.setA3_04_TabRig_Passaporto_N_06_nome_passeggero_1("");
  ControlloMyContext.setA3_04_TabRig_Passaporto_N_07_cittadinanza_passeggero_1(
    ""
  );
  ControlloMyContext.setA3_04_TabRig_Passaporto_N_08_data_nascita_passeggero_1(
    ""
  );
  ControlloMyContext.setA3_04_TabRig_Passaporto_N_09_luogo_nascita_passeggero_1(
    ""
  );
  ControlloMyContext.setA3_04_TabRig_Passaporto_N_10_sesso_passeggero_1("");
  ControlloMyContext.setA3_04_TabRig_Passaporto_N_11_data_emissione_documento_passeggero_1(
    ""
  );
  ControlloMyContext.setA3_04_TabRig_Passaporto_N_12_data_scadenza_documento_passeggero_1(
    ""
  );
  ControlloMyContext.setA3_04_TabRig_Passaporto_N_13_autorita_emittente_passeggero_1(
    ""
  );
  ControlloMyContext.setA3_04_TabRig_Passaporto_N_02_tipo_passeggero_2("");
  ControlloMyContext.setA3_04_TabRig_Passaporto_N_03_codice_paese_passeggero_2(
    ""
  );
  ControlloMyContext.setA3_04_TabRig_Passaporto_N_04_numero_passaporto_passeggero_2(
    ""
  );
  ControlloMyContext.setA3_04_TabRig_Passaporto_N_05_cognome_passeggero_2("");
  ControlloMyContext.setA3_04_TabRig_Passaporto_N_06_nome_passeggero_2("");
  ControlloMyContext.setA3_04_TabRig_Passaporto_N_07_cittadinanza_passeggero_2(
    ""
  );
  ControlloMyContext.setA3_04_TabRig_Passaporto_N_08_data_nascita_passeggero_2(
    ""
  );
  ControlloMyContext.setA3_04_TabRig_Passaporto_N_09_luogo_nascita_passeggero_2(
    ""
  );
  ControlloMyContext.setA3_04_TabRig_Passaporto_N_10_sesso_passeggero_2("");
  ControlloMyContext.setA3_04_TabRig_Passaporto_N_11_data_emissione_documento_passeggero_2(
    ""
  );
  ControlloMyContext.setA3_04_TabRig_Passaporto_N_12_data_scadenza_documento_passeggero_2(
    ""
  );
  ControlloMyContext.setA3_04_TabRig_Passaporto_N_13_autorita_emittente_passeggero_2(
    ""
  );
  ControlloMyContext.setA3_04_TabRig_Passaporto_N_02_tipo_passeggero_3("");
  ControlloMyContext.setA3_04_TabRig_Passaporto_N_03_codice_paese_passeggero_3(
    ""
  );
  ControlloMyContext.setA3_04_TabRig_Passaporto_N_04_numero_passaporto_passeggero_3(
    ""
  );
  ControlloMyContext.setA3_04_TabRig_Passaporto_N_05_cognome_passeggero_3("");
  ControlloMyContext.setA3_04_TabRig_Passaporto_N_06_nome_passeggero_3("");
  ControlloMyContext.setA3_04_TabRig_Passaporto_N_07_cittadinanza_passeggero_3(
    ""
  );
  ControlloMyContext.setA3_04_TabRig_Passaporto_N_08_data_nascita_passeggero_3(
    ""
  );
  ControlloMyContext.setA3_04_TabRig_Passaporto_N_09_luogo_nascita_passeggero_3(
    ""
  );
  ControlloMyContext.setA3_04_TabRig_Passaporto_N_10_sesso_passeggero_3("");
  ControlloMyContext.setA3_04_TabRig_Passaporto_N_11_data_emissione_documento_passeggero_3(
    ""
  );
  ControlloMyContext.setA3_04_TabRig_Passaporto_N_12_data_scadenza_documento_passeggero_3(
    ""
  );
  ControlloMyContext.setA3_04_TabRig_Passaporto_N_13_autorita_emittente_passeggero_3(
    ""
  );
  ControlloMyContext.setA3_04_TabRig_Passaporto_N_02_tipo_passeggero_4("");
  ControlloMyContext.setA3_04_TabRig_Passaporto_N_03_codice_paese_passeggero_4(
    ""
  );
  ControlloMyContext.setA3_04_TabRig_Passaporto_N_04_numero_passaporto_passeggero_4(
    ""
  );
  ControlloMyContext.setA3_04_TabRig_Passaporto_N_05_cognome_passeggero_4("");
  ControlloMyContext.setA3_04_TabRig_Passaporto_N_06_nome_passeggero_4("");
  ControlloMyContext.setA3_04_TabRig_Passaporto_N_07_cittadinanza_passeggero_4(
    ""
  );
  ControlloMyContext.setA3_04_TabRig_Passaporto_N_08_data_nascita_passeggero_4(
    ""
  );
  ControlloMyContext.setA3_04_TabRig_Passaporto_N_09_luogo_nascita_passeggero_4(
    ""
  );
  ControlloMyContext.setA3_04_TabRig_Passaporto_N_10_sesso_passeggero_4("");
  ControlloMyContext.setA3_04_TabRig_Passaporto_N_11_data_emissione_documento_passeggero_4(
    ""
  );
  ControlloMyContext.setA3_04_TabRig_Passaporto_N_12_data_scadenza_documento_passeggero_4(
    ""
  );
  ControlloMyContext.setA3_04_TabRig_Passaporto_N_13_autorita_emittente_passeggero_4(
    ""
  );
  ControlloMyContext.setA3_04_TabRig_Passaporto_N_02_tipo_passeggero_5("");
  ControlloMyContext.setA3_04_TabRig_Passaporto_N_03_codice_paese_passeggero_5(
    ""
  );
  ControlloMyContext.setA3_04_TabRig_Passaporto_N_04_numero_passaporto_passeggero_5(
    ""
  );
  ControlloMyContext.setA3_04_TabRig_Passaporto_N_05_cognome_passeggero_5("");
  ControlloMyContext.setA3_04_TabRig_Passaporto_N_06_nome_passeggero_5("");
  ControlloMyContext.setA3_04_TabRig_Passaporto_N_07_cittadinanza_passeggero_5(
    ""
  );
  ControlloMyContext.setA3_04_TabRig_Passaporto_N_08_data_nascita_passeggero_5(
    ""
  );
  ControlloMyContext.setA3_04_TabRig_Passaporto_N_09_luogo_nascita_passeggero_5(
    ""
  );
  ControlloMyContext.setA3_04_TabRig_Passaporto_N_10_sesso_passeggero_5("");
  ControlloMyContext.setA3_04_TabRig_Passaporto_N_11_data_emissione_documento_passeggero_5(
    ""
  );
  ControlloMyContext.setA3_04_TabRig_Passaporto_N_12_data_scadenza_documento_passeggero_5(
    ""
  );
  ControlloMyContext.setA3_04_TabRig_Passaporto_N_13_autorita_emittente_passeggero_5(
    ""
  );

  //A3_05_TabRig_CartaCircolazione---------------------------------------------------------------

  ControlloMyContext.setA3_05_TabRig_CartaCircolazione_N_01_targa_veicolo("");
  ControlloMyContext.setA3_05_TabRig_CartaCircolazione_N_02_data_prima_immatricolazione(
    ""
  );
  ControlloMyContext.setA3_05_TabRig_CartaCircolazione_N_03_nome_proprietario(
    ""
  );
  ControlloMyContext.setA3_05_TabRig_CartaCircolazione_N_04_cognome_proprietario(
    ""
  );
  ControlloMyContext.setA3_05_TabRig_CartaCircolazione_N_05_data_nascita("");
  ControlloMyContext.setA3_05_TabRig_CartaCircolazione_N_06_luogo_nascita("");
  ControlloMyContext.setA3_05_TabRig_CartaCircolazione_N_07_marca_modello_veicolo(
    ""
  );
  ControlloMyContext.setA3_05_TabRig_CartaCircolazione_N_08_numero_telaio("");
  ControlloMyContext.setA3_05_TabRig_CartaCircolazione_N_09_categorie_veicolo(
    ""
  );
  ControlloMyContext.setA3_05_TabRig_CartaCircolazione_N_10_destinazione_uso(
    ""
  );
  ControlloMyContext.setA3_05_TabRig_CartaCircolazione_N_11_emissioni("");
  ControlloMyContext.setA3_05_TabRig_CartaCircolazione_N_12_classe_ambientale(
    ""
  );
  ControlloMyContext.setA3_05_TabRig_CartaCircolazione_N_13_massa_a_vuoto("");
  ControlloMyContext.setA3_05_TabRig_CartaCircolazione_N_14_numero_assi("");
  ControlloMyContext.setA3_05_TabRig_CartaCircolazione_N_15_massa_massima_a_carico_tecnicamente_ammissibile(
    ""
  );
  ControlloMyContext.setA3_05_TabRig_CartaCircolazione_N_16_massa_massima_a_rimorchio_ammissibile_con_rimorchio_frenato(
    ""
  ),
    ControlloMyContext.setA3_05_TabRig_CartaCircolazione_N_17_massa_massima_a_rimorchio_ammissibile_con_rimorchio_non_frenato(
      ""
    );
  ControlloMyContext.setA3_05_TabRig_CartaCircolazione_N_18_cilindrata("");
  ControlloMyContext.setA3_05_TabRig_CartaCircolazione_N_19_potenza_netta_kW(
    ""
  );
  ControlloMyContext.setA3_05_TabRig_CartaCircolazione_N_20_tipo_combustibile_alimentazione(
    ""
  );
  ControlloMyContext.setA3_05_TabRig_CartaCircolazione_N_21_numero_id_motore(
    ""
  );
  ControlloMyContext.setA3_05_TabRig_CartaCircolazione_N_22_rapporto_potenza_massa_in_kW_solo_motocicli(
    ""
  );
  ControlloMyContext.setA3_05_TabRig_CartaCircolazione_N_23_numeri_posti_a_sedere(
    undefined
  );
  ControlloMyContext.setA3_05_TabRig_CartaCircolazione_N_24_Emissioni_co2_g_km(
    undefined
  );
  ControlloMyContext.setA3_05_TabRig_CartaCircolazione_N_25_tipo_mezzo("");
  ControlloMyContext.setA3_05_TabRig_CartaCircolazione_id_record(undefined);

  //A3_06_TabRig_CertificatoAssicurazione---------------------------------------------------------------

  ControlloMyContext.setA3_06_TabRig_CertificatoAssicurazione_N_01_nome("");
  ControlloMyContext.setA3_06_TabRig_CertificatoAssicurazione_N_02_cognome("");
  ControlloMyContext.setA3_06_TabRig_CertificatoAssicurazione_N_03_indirizzo_residenza(
    ""
  );
  ControlloMyContext.setA3_06_TabRig_CertificatoAssicurazione_N_04_nome_compagnia_assicurativa(
    ""
  );
  ControlloMyContext.setA3_06_TabRig_CertificatoAssicurazione_N_05_targa_veicolo(
    ""
  );
  ControlloMyContext.setA3_06_TabRig_CertificatoAssicurazione_N_06_numero_polizza(
    ""
  );
  ControlloMyContext.setA3_06_TabRig_CertificatoAssicurazione_N_07_data_inizio_polizza(
    undefined
  );
  ControlloMyContext.setA3_06_TabRig_CertificatoAssicurazione_N_08_data_fine_polizza(
    undefined
  );
  ControlloMyContext.setA3_06_TabRig_CertificatoAssicurazione_N_09_marca_modello_veicolo(
    ""
  );
  ControlloMyContext.setA3_06_TabRig_CertificatoAssicurazione_N_10_cilindrata(
    ""
  );
  ControlloMyContext.setA3_06_TabRig_CertificatoAssicurazione_N_11_potenza("");
  ControlloMyContext.setA3_06_TabRig_CertificatoAssicurazione_N_12_carburante(
    ""
  );
  ControlloMyContext.setA3_06_TabRig_CertificatoAssicurazione_id_record(
    undefined
  );

  //A4_01_TabRig_Immagini---------------------------------------------------------------

  ControlloMyContext.setA4_01_TabRig_Immagini_M_immagine_01("");
  ControlloMyContext.setA4_01_TabRig_Immagini_M_immagine_02("");
  ControlloMyContext.setA4_01_TabRig_Immagini_M_immagine_03("");
  ControlloMyContext.setA4_01_TabRig_Immagini_M_immagine_04("");
  ControlloMyContext.setA4_01_TabRig_Immagini_M_immagine_05("");
  ControlloMyContext.setA4_01_TabRig_Immagini_M_immagine_06("");
  ControlloMyContext.setA4_01_TabRig_Immagini_M_immagine_07("");
  ControlloMyContext.setA4_01_TabRig_Immagini_M_immagine_08("");
  ControlloMyContext.setA4_01_TabRig_Immagini_M_immagine_09("");
  ControlloMyContext.setA4_01_TabRig_Immagini_M_immagine_10("");
  ControlloMyContext.setA4_01_TabRig_Immagini_M_immagine_11("");
  ControlloMyContext.setA4_01_TabRig_Immagini_M_immagine_12("");
  ControlloMyContext.setA4_01_TabRig_Immagini_M_immagine_13("");
  ControlloMyContext.setA4_01_TabRig_Immagini_M_immagine_14("");
  ControlloMyContext.setA4_01_TabRig_Immagini_M_immagine_15("");
  ControlloMyContext.setA4_01_TabRig_Immagini_M_immagine_16("");
  ControlloMyContext.setA4_01_TabRig_Immagini_M_immagine_17("");
  ControlloMyContext.setA4_01_TabRig_Immagini_M_immagine_18("");
  ControlloMyContext.setA4_01_TabRig_Immagini_M_immagine_19("");
  ControlloMyContext.setA4_01_TabRig_Immagini_M_immagine_20("");
  ControlloMyContext.setA4_01_TabRig_Immagini_M_immagine_21("");
  ControlloMyContext.setA4_01_TabRig_Immagini_M_immagine_22("");
  ControlloMyContext.setA4_01_TabRig_Immagini_M_immagine_23("");
  ControlloMyContext.setA4_01_TabRig_Immagini_M_immagine_24("");
  ControlloMyContext.setA4_01_TabRig_Immagini_M_immagine_25("");
  ControlloMyContext.setA4_01_TabRig_Immagini_M_immagine_26("");
  ControlloMyContext.setA4_01_TabRig_Immagini_M_immagine_27("");
  ControlloMyContext.setA4_01_TabRig_Immagini_M_immagine_28("");
  ControlloMyContext.setA4_01_TabRig_Immagini_M_immagine_29("");
  ControlloMyContext.setA4_01_TabRig_Immagini_M_immagine_30("");
};
export default resetContext;
